config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  root 'users#home'

  # start of clearance routes
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end


  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"


# end of clearance routes

  resources :listings 
  get "/mylistings" => "listings#userlisting", :as => :listing_user

  resources :users, only: [:edit, :update, :index]
  get '/users' => 'users#index', :as => :users_index

  resources :bookings, only: [:create, :destroy, :show, :edit, :update, :index]


  resources :searches, only: [:create]
  post '/search', to: 'listings#search', as: 'search' 

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  

  # get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  # delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  get '/:id', to: 'listings#show'


  post 'braintree/checkout'
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  paginates_per 10
  mount_uploaders :photos, AvatarUploader

 def self.search(search)
 	where("state LIKE ? OR address1 LIKE ?", "%#{search}%", "%#{search}%")
 end



end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :check_owner, only: [:edit, :update, :destroy] 




  # GET /listings
  # GET /listings.json
  def index
    # @listings = Listing.all
    @listings=Listing.order(:id)
    # @listings=@listings.city(params[:city]) if params[:city].present?
  end

  def search
    if params[:search]
      @listings = Listing.search(params[:search]).order("created_at DESC")
    else
      @listings = Listing.all.order("created_at DESC")
    end

    render 'users/home'
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @booking = @listing.bookings.new
  end

  # GET /listings/new
  def new
    @listing = Listing.new
    # allowed?(action: "new", user: current_user)
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    # @listing = Listing.new(listing_params)
    @listing = current_user.listings.new(listing_params)
    # @listing.update(photos: listings_params[:photos])
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def userlisting
    @listings = current_user.listings
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def check_owner
      unless @listing.user_id == current_user.id
        redirect_to listings_path, notice: "You are not allowed to access that page."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:address1, :address2, :postal_code, :state, :country, :price, :room_type, :description, :availability, :bedroom, :bathroom, :max_num_guests, {photos:[]})
    end

    def filtering_params(params)
      # params.slice(:city)
      params(:city)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(listing) do |f| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="field">
    <%= f.label :address1 %>
    <%= f.text_field :address1 %>
  </div>

  <div class="field">
    <%= f.label :address2 %>
    <%= f.text_field :address2 %>
  </div>

  <div class="field">
    <%= f.label :postal_code %>
    <%= f.number_field :postal_code %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :room_type %>
    <%= f.text_field :room_type %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :availability %>
    <%= f.date_select :availability %>
  </div>

  <div class="field">
    <%= f.label :bedroom %>
    <%= f.number_field :bedroom %>
  </div>

  <div class="field">
    <%= f.label :bathroom %>
    <%= f.number_field :bathroom %>
  </div>

  <div class="field">
    <%= f.label :max_num_guests %>
    <%= f.number_field :max_num_guests %>
  </div>

  <div class="field">
    <%= f.file_field :photos, multiple: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/backup.erb
<!-- this is the index.html.erb (listing) -->

<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="table-responsive">
        <table class="table table-bordered table hover">
  
    <thead>
      <tr>
        <th>User</th> 
        <th>Address1</th>
        <th>Address2</th>
        <th>Postal code</th>
        <th>State</th>
        <th>Country</th>
        <th>Price</th>
        <th>Room type</th>
        <th>Description</th>
        <th>Availability</th>
        <th>Bedroom</th>
        <th>Bathroom</th>
        <th>Preview Pic</th>
      </tr>
    </thead> 


     <tbody> 
      <% @listings.each do |listing| %>
         <tr> 
          <td><%= listing.user.first_name %></td> 
          <td><%= listing.address1 %></td>
          <td><%= listing.address2 %></td>
          <td><%= listing.postal_code %></td>
          <td><%= listing.state %></td>
          <td><%= listing.country %></td>
          <td><%= listing.price %></td>
          <td><%= listing.room_type %></td>
          <td><%= listing.description %></td>
          <td><%= listing.availability %></td>
          <td><%= listing.bedroom %></td>
          <td><%= listing.bathroom %></td>
           <td><% if listing.photos.length > 0 %>
              <%= image_tag listing.photos.first, id:"listing_preview"%>
              <% else %>
              <img id="listing_preview" src="/assets/no-preview.jpg">
              <% end %>
          </td>  
                   
          <% if current_user.id == listing.user_id %>
            <td><%= link_to 'Show', listing %></td>
            <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
            <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
 </div> 
 </div>
 </div>
 </div> 

<%= paginate @listings %>

<br>

<%= link_to 'New Listing', new_listing_path %>





<!-- second attempt -->

<!-- <div class="cards row">
     <%# @listings.each_with_index do |listing, i| %>
  <div class="card col-md-3" style="height: 300px; padding-top: 8px;" >
   <div id= "card_margin" >
      <%# if listing.photos.length > 0 %>
      <%=# image_tag listing.photos.first.carousel, id:"card_listing_preview"%>
      <%# else %>
        <img id="card_listing_preview" src="/assets/no-preview.jpg">
      <%# end %> 
     </tr> 
    <div class="card-title">
      <a href="#" class="toggle-info btn">
        <span class="left"></span>
        <span class="right"></span>
      </a>
      <h2>
          <p>RM <%= listing.price %></p>
          <%= listing.state %>
          <small>Image from unsplash.com</small>
      </h2>
    </div> -->
    <!-- <div class="card-flap flap1">
      <div class="card-description">
        <%= listing.address1 %>
        <%= listing.room_type %>
        <%= listing.description %>
        </div>
      <div class="card-flap flap2">
        <div class="card-actions">
          <%#= link_to 'Read more', listing, class: 'btn', style: 'z-index:9999;' %>
          <%#= link_to 'read more', show_path %>
        </div>
      </div>
    </div>
    </div> --> 
   <!-- </div> 
  <%# if (i + 1) % 4 == 0  %>
     </div>
    <div class="cards row"> 
 

<%# if current_user.id == listing.user_id %>
   <%#= link_to 'Show', listing %>
    <%#= link_to 'Edit', edit_listing_path(listing) %>
    <%#= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %>
  <%# end %>


  <%# end %>

   -->


   <!-- Third attemp -->
   <!-- <p id="notice"><%= notice %></p>

<h1>Listings</h1>
 -->
<!-- Media, Title, and Description area -->
      <!-- <div class="row" style="height:600px;">
          <%# @listings.each_with_index do |listing, i| %>
          <div class="card col-md-3 col-sm-10" style="padding-top: 8px;" >
            <div class="pmd-card pmd-card-default pmd-z-depth" style="height:400px;">
                 -->
                  <!-- <div id= "card_margin" > -->

  <!-- Card media -->
                  <!-- <div class="pmd-card-media" style="height:40%">
                      <%# if listing.photos.length > 0 %>
                        <%#= image_tag(listing.photos.first.carousel,:id=>"card_listing_preview")%>
                      <%# else %> -->
                        <!-- <img id="card_listing_preview" src="/assets/no-preview.jpg"> -->
                        <!-- <img width="1184" height="666" class="img-responsive" src="http://propeller.in/assets/images/profile-pic.png">
                      <%# end %>  -->
    
        <!-- <img width="1184" height="666" class="img-responsive" src="http://propeller.in/assets/images/profile-pic.png"> -->
                  <!-- </div> -->
    
    <!-- Card header -->
      <!-- <div class="pmd-card-title">
          <h2 class="pmd-card-title-text">
              <p>RM <%= listing.price %></p>
              <%= listing.state %> -->
              <!-- <small>Image from unsplash.com</small> -->
         <!--  </h2> -->
        <!-- <h2 class="pmd-card-title-text">Title goes here</h2>
        <span class="pmd-card-subtitle-text">Secondary text</span>   -->
      <!-- </div> -->
    
    <!-- Card action -->
     <!--  <div class="pmd-card-actions">
          <%#= link_to listing do %><button class="btn pmd-btn-flat pmd-ripple-effect btn-primary" type="button">Primary</button><%# end %>
          <button type="button" class="btn pmd-btn-flat pmd-ripple-effect btn-default">Action</button>
      </div>
    </div> -->
    <%# if (i + 1) % 4 == 0  %>
   <!--  </div> -->
   <!--  <div class="cards row">  -->
 <%# end %> 

  
  <!-- </div> -->

<%# if current_user.id == listing.user_id %>
            <!-- <td><%#= link_to 'Show', listing %></td>
            <td><%#= link_to 'Edit', edit_listing_path(listing) %></td>
            <td><%#= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <%# end %>
 -->



  <!-- </div> -->
<%# end %>

 <!-- </div>  -->


           
  


 

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
 <p id="notice"><%= notice %></p>

<h1>Listings</h1>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="table-responsive">
        <table class="table table-bordered table hover">
  
    <thead>
      <tr>
        <th>User</th> 
        <th>Address1</th>
        <th>Address2</th>
        <th>Postal code</th>
        <th>State</th>
        <th>Country</th>
        <th>Price</th>
        <th>Room type</th>
        <th>Description</th>
        <th>Availability</th>
        <th>Bedroom</th>
        <th>Bathroom</th>
        <th>Preview Pic</th>
      </tr>
    </thead> 


     <tbody> 
      <% @listings.each do |listing| %>
         <tr> 
          <td><%= listing.user.username %></td> 
          <td><%= listing.address1 %></td>
          <td><%= listing.address2 %></td>
          <td><%= listing.postal_code %></td>
          <td><%= listing.state %></td>
          <td><%= listing.country %></td>
          <td><%= listing.price %></td>
          <td><%= listing.room_type %></td>
          <td><%= listing.description %></td>
          <td><%= listing.availability %></td>
          <td><%= listing.bedroom %></td>
          <td><%= listing.bathroom %></td>
           <td><% if listing.photos.length > 0 %>
              <%= image_tag listing.photos.first, id:"listing_preview"%>
              <% else %>
              <img id="listing_preview" src="/assets/no-preview.jpg">
              <% end %>
          </td>  
             <td><%= link_to 'Show', listing %></td>      
          <% if current_user.id == listing.user_id %>
            
            <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
            <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
 </div> 
 </div>
 </div>
 </div> 

  
    
 

<%= paginate @listings %>

<br>

<%= link_to 'New Listing', new_listing_path %>



 

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-8">
      <% if @listing.photos.length > 0 %>  
        <div class="container" style="height:300px; width:600px">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
          <ol class="carousel-indicators">

            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <% t = @listing.photos.length-1 %>
              <% for y in 1..t do%>
           <li data-target="#myCarousel" data-slide-to="<%= y %>"></li>
              <% end %>
          </ol>
<!-- Wrapper for slides -->
  
      <div class="carousel-inner" style="height:300px">   
        <div class="item active">
          <%= image_tag @listing.photos.first.carousel.url %>  
        </div>
          <% for i in 1..t do%>
        <div class="item">
          <%= image_tag @listing.photos[i].carousel.url%>
        </div>
        <% end %>  
      </div> 

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<% end %>
</div>
<div class="col-md-4">
<p>
  <strong>User:</strong>
  <%= @listing.user[:username] %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @listing.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @listing.address2 %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @listing.postal_code %>
</p>

<p>
  <strong>State:</strong>
  <%= @listing.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @listing.country %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Room type:</strong>
  <%= @listing.room_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @listing.availability %>
</p>

<p>
  <strong>Bedroom:</strong>
  <%= @listing.bedroom %>
</p>

<p>
  <strong>Bathroom:</strong>
  <%= @listing.bathroom %>
</p>

<p>
  <strong>Max no. Guest:</strong>
  <%= @listing.max_num_guests %>
</p>

</div>
</div>


 



<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>
<%= render "bookings/form" %>

app/views/listings/userlisting.html.erb
<p>testing</p>
<br>



	<% end %>

	<div class="row" style="margin-top: 20px;">
    <div class="col-xs-12">
      <div class="table-responsive">
        <table class="table table-bordered table hover">
  
    <thead>
      <tr>
        <th>User</th> 
        <th>Address1</th>
        <th>Address2</th>
        <th>Postal code</th>
        <th>State</th>
        <th>Country</th>
        <th>Price</th>
        <th>Room type</th>
        <th>Description</th>
        <th>Availability</th>
        <th>Bedroom</th>
        <th>Bathroom</th>
        <th>Preview Pic</th>
        <th>Action</th>
      </tr>
    </thead> 


     <tbody> 
	      <% @listings.each do |listing| %>
         <tr> 
          <td><%= listing.user.username %></td> 
          <td><%= listing.address1 %></td>
          <td><%= listing.address2 %></td>
          <td><%= listing.postal_code %></td>
          <td><%= listing.state %></td>
          <td><%= listing.country %></td>
          <td><%= listing.price %></td>
          <td><%= listing.room_type %></td>
          <td><%= listing.description %></td>
          <td><%= listing.availability %></td>
          <td><%= listing.bedroom %></td>
          <td><%= listing.bathroom %></td>
           <td><% if listing.photos.length > 0 %>
              <%= image_tag listing.photos.first, id:"listing_preview"%>
              <% else %>
              <img id="listing_preview" src="/assets/no-preview.jpg">
              <% end %>
          </td>  
             <td><%= link_to 'Show', listing %></td>      
          <% if current_user.id == listing.user_id %>
            
            <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
            <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
 </div> 
 </div>
 </div>