config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  root 'users#home'

  # start of clearance routes
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end


  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"


# end of clearance routes

  resources :listings 
  get "/mylistings" => "listings#userlisting", :as => :listing_user

  resources :users, only: [:edit, :update, :index]
  get '/users' => 'users#index', :as => :users_index

  resources :bookings, only: [:create, :destroy, :show, :edit, :update, :index]


  resources :searches, only: [:create]
  post '/search', to: 'listings#search', as: 'search' 

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  

  # get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  # delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  get '/:id', to: 'listings#show'


  post 'braintree/checkout'
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  validate :check_overlapping_dates
  validate :check_max_num_guests
  #validate num_guests is not negative
  #validate start__date should be after today
   paginates_per 5


   def check_overlapping_dates
   	#compare new booking with existing booking
   	
   	self.listing.bookings.each do |old_booking|
   		if overlap?(self, old_booking)
   			
				return self.errors.add(:overlapping_dates, "The booking dates conflict with existing bookings")
			end
		end
   end

  def overlap?(x,y)
		(x.start_date - y.end_date) * (y.start_date - x.end_date) > 0
	end

	def check_max_num_guests
		max_num_guests = self.listing.max_num_guests
		return if self.num_guests < max_num_guests	
		self.errors.add(:max_num_guests,"Number of max guests exceeded")
	end

	def total_price
		price = self.listing.price
		num_dates = (self.start_date..self.end_date).to_a.length
		return price * num_dates
	end
end



#    before_create: check_date_availability

# def self.check_date_availability(booking_params)
#   bookings = Booking.where('start_date < ? OR end_date > ?', self.start_date, self.end_date)
#   return bookings.empty?
# end
# end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  

def index
    # @listings = Listing.all
    @bookings=Booking.order(:id).page params[:page]
  end

def create
	@listing = Listing.find(params[:booking][:listing_id])   
	@booking = current_user.bookings.new(booking_params)
  @booking.listing = @listing

  
	# @booking.update(total_price: (@booking.end_date - @booking.start_date).to_i * @listing.price)
 
	if @booking.save
     #BookingMailer.booking_email(@booking.user ,@listing.user,@booking.id).deliver_now
     BookingJobJob.perform_later(@booking.user ,@listing.user,@booking.id).
		# redirect_to listing_path(@listing)
		 redirect_to booking_path(@booking), notice: "Your reservation has been created..."
	else
    errors = @booking.errors.messages
		render "listings/show"
	end
end

def show
    @booking = Booking.find(params[:id])

 end

 def edit
 		@booking = Booking.find(params[:id])
    @listing = Listing.find(@booking.listing_id)
 end

def update
		@booking = Booking.find(params[:id])
    @listing = Listing.find(@booking.listing_id)
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        flash[:danger] = "Booking is not available on thay dates"
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end


def destroy
  @booking = Booking.find(params[:id])
  @booking.destroy
  flash[:success] = "Booking deleted"
  redirect_to bookings_path
end

def booking_params
	params.require(:booking).permit(:num_guests, :start_date, :end_date, :listing_id)
end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for (@booking) do |f| %>
<%= f.hidden_field :listing_id, value: @listing.id %>

  <div class="field">
    <%= f.label :num_guests %>
    <%#= f.num_guests :num_guests %>
    <%#= f.select :num_guests, ["1","2","3","4","5"], :prompt => "Select one"%>
    <%= f.select :num_guests, (((1..@listing.max_num_guests).to_a).map!{|i| i.to_s }), :prompt => "Select one"%>
    
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_field :end_date %>
  </div>

  

  <div class="actions">
    <%= f.submit "Submit Booking" %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1>Bookings</h1>
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="table-responsive">
        <table class="table table-bordered table hover">
  
    <thead>
      <tr>
        <!-- <th>User</th> -->
        <th>Num of Guest</th>
        <th>Check in date</th>
        <th>Check out date</th>
        <th>Action</th>
      </tr>
    </thead>


    <tbody>
      <% @bookings.each do |booking| %>
        <tr>
          <td><%= booking.num_guests %></td>
          <td><%= booking.start_date.strftime('%d %B %Y') %></td>
          <td><%= booking.end_date.strftime('%d %B %Y') %></td>
          
                   
          <% if current_user.id == booking.user_id %>
            <td><%= link_to 'Show', booking %></td>
            <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
            <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
 </div> 
 </div>
 </div>
 </div>


<%= paginate @bookings %>

app/views/bookings/show.html.erb
<% if @booking.listing.photos.length > 0 %>
	<%= image_tag @booking.listing.photos.first, id:"listing_preview"%>
<% else %>
  <img id="listing_preview" src="/assets/no-preview.jpg">
<% end %>


<p>
  <strong>Num of guest:</strong>
  <%= @booking.num_guests %>
</p>

<p>
  <strong>Check in date:</strong>
  <%= @booking.start_date %>
</p>

<p>
  <strong>Check out date:</strong>
  <%= @booking.end_date %>
</p>

<p>
	<strong>Total no. of Days</strong>
	<%= (@booking.end_date - @booking.start_date).to_i %>
	
</p>

<p>
	<strong>Total Price</strong>
	<%= @booking.total_price %>
</p>

<%= link_to "Make Payment", braintree_new_path %>

<% if @booking.start_date != DateTime.now.to_date %>
<%= link_to 'Edit', edit_booking_path(@booking) %> 
<% end %>
<%= link_to 'Back', bookings_path %>