config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  root 'users#home'

  # start of clearance routes
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end


  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"


# end of clearance routes

  resources :listings 
  get "/mylistings" => "listings#userlisting", :as => :listing_user

  resources :users, only: [:edit, :update, :index]
  get '/users' => 'users#index', :as => :users_index

  resources :bookings, only: [:create, :destroy, :show, :edit, :update, :index]


  resources :searches, only: [:create]
  post '/search', to: 'listings#search', as: 'search' 

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  

  # get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  # delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  get '/:id', to: 'listings#show'


  post 'braintree/checkout'
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  paginates_per 10

  mount_uploader :avatar, AvatarUploader
  
  
	# has_secure_password
	has_many :listings, dependent: :destroy
	has_many :bookings, dependent: :destroy
	

	validates :username, presence: true #{message: "Please fill-in all fields" }
	# validates :email, uniqueness: { message: "must be new"}
	# validates :email, format: { with: /\w*@.*\.\w*/, message: "Invalid email address" } 
	validates :password, length: { minimum: 6, message: "Password must be at least 6 characters" }, on: :create

#In app/models/user.rb    
has_many :authentications, :dependent => :destroy

  def self.create_with_auth_and_hash(authentication, auth_hash)
      user = User.create!(username: auth_hash["name"], email: auth_hash["extra"]["raw_info"]["email"], password: SecureRandom.hex(5))
      user.authentications << (authentication)      
      return user
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

# you can also explicitly define enum as:  enum access_level: [:employee => 0, :company_admin => 1, :super_admin => 2}
  enum access_level: [:customer, :moderator, :admin]


end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:create, :new]
    skip_before_action :require_login, only: [:create, :new], raise: false
    skip_before_action :authorize, only: [:create, :new], raise: false
  else
    before_filter :redirect_signed_in_users, only: [:create, :new]
    skip_before_filter :require_login, only: [:create, :new], raise: false
    skip_before_filter :authorize, only: [:create, :new], raise: false
  end

  def show
      @user = User.find(params[:id])
  end

  def new
    @user = User.new
    render template: "users/new"
  end

  def create
    @user = User.new(user_from_params)

    if @user.save
      sign_in @user
      # redirect_back_or url_after_create
      redirect_to listing_path
    else
       flash[:notice] = "Make sure you include your name and a valid email address"
      # respond_to do |format|
      # format.html {redirect_to @user}
        # format.js
       render template: "users/new"
      # end
    end
  end


  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
    params.require(:user).permit(:avatar, :email, :password, :username)
    # email = user_params.delete(:email)
    # password = user_params.delete(:password)
    # username = user_params.delete(:username)

    # Clearance.configuration.user_model.new(user_params).tap do |user|
    #   user.email = email
    #   user.password = password
    #   user.username = username
    # end
  end

  # def user_params
  #   params[Clearance.configuration.user_parameter] || Hash.new
  # end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
	before_action :require_login
  before_action :find_user, only: [:show, :edit, :update]
	
  def home
    @users=User.all
    @listings=Listing.order(:id).page params[:page]
    # @users = User.order(:name).page params[:page]
    
  end


	def index
		@users=current_user
    @listings=Listing.order(:id).page params[:page]
		# @users = User.order(:name).page params[:page]
    
	end

  def show
    @bookings = @user.bookings
  end


	def edit
   
  end

  def update
  
    p edit_user_params
    if @user.update(edit_user_params)
    	flash[:notice] = "Your profile has been updated"
    	redirect_to root_path
    else
    	flash.now[:notice] = "There are errors."
    	p @user.errors
    	render :edit
    end
  end

	# def create
	# 	@user=User.new(param[:user])
	# 	@user.save
	# end

	private

  def find_user
    @user = User.find(params[:id])
  end

	# def user_from_params
 #    params.require(:user).permit(:avatar, :email, :password, :username)
 #  end

  def edit_user_params
  	params.require(:user).permit(:avatar, :email, :username)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :username %>
  <%= form.text_field :username, type: 'username' %>
</div>


<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="image-field">
	<%= form.label :avatar %>
  <%= form.file_field :avatar %>
</div>

app/views/users/edit.html.erb
<%= form_for @user, html: {multipart: true} do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>
<%end%>

app/views/users/home.html.erb
<p class='text-center'>testing</p>
<br>
<br>
<H1>HOME</H1>

<%#= form_for :search, url: searches_path do |form| %>
         <%#= form.label :price %>
         <%#= form.text_field :price %>

         <%#= form.label :city %>
         <%#= form.text_field :city %>

         <%#= form.submit "Submit" %>              
         <%# end %> 

         <%= form_tag(search_path, :method => "post", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Listings" %>
    <%= submit_tag "Search", :name => nil %>

   <% if @listings.blank? %>
        <h4>There are no listings containing the term <%= params[:search] %>.</h4>
    <% end %>
    <% end %>

<div class="cards row">
  <% @listings.each_with_index do |listing, i| %>
  <!-- Card media -->
      <div class="card col-md-3" style="height: 300px; padding-top: 8px;" >
      <div class="pmd-card pmd-card-default pmd-z-depth">
        <div id= "card_margin" >
          <div class="pmd-card-media">
            <% if listing.photos.length > 0 %>
              <%= image_tag listing.photos.first.carousel, id:"card_listing_preview"%>
            <% else %>
              <img id="card_listing_preview" src="http://propeller.in/assets/images/profile-pic.png">
            <% end %> 
        <!-- <img width="1184" height="666" class="img-responsive" src="http://propeller.in/assets/images/profile-pic.png"> -->
          </div>
    
    <!-- Card header -->
          <div class="pmd-card-title">
        <h2 class="pmd-card-title-text"><%= listing.room_type %></h2>
        <span class="pmd-card-subtitle-text" style="color:red ">MYR <%= listing.price %></span><br> 
        <span class="pmd-card-subtitle-text"><%= listing.state %></span>   
          </div>
    
    <!-- Card action -->
      <div class="pmd-card-actions">

<!-- <button data-target="#media-dialog" data-toggle="modal" class="btn pmd-ripple-effect btn-primary pmd-z-depth" type="button">Media Modal</button>
<div tabindex="-1" class="modal fade" id="media-dialog" style="display: none;" aria-hidden="true"> 
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="pmd-modal-media"> <img width="1184" height="666" class="img-responsive" src="http://propeller.in/assets/images/profile-pic.png"> </div>
      <div class="pmd-card-title">
        <h2 class="pmd-card-title-text">Title goes here</h2>
        <span class="pmd-card-subtitle-text">Secondary text</span> </div>
      <div class="pmd-modal-action">
        <button data-dismiss="modal"  class="btn pmd-ripple-effect btn-primary pmd-btn-flat" type="button">Primary</button>
        <button data-dismiss="modal"  class="btn pmd-ripple-effect btn-default pmd-btn-flat" type="button">Action</button>
      </div>
      <div class="modal-body"> Cards provide context and an entry point to more robust information and views. Don't overload cards with extraneous information or actions. </div>
    </div>
  </div> 
</div>
 -->






        <button class="btn pmd-btn-flat pmd-ripple-effect btn-primary" type="button"><%= link_to listing do %>More Info...<% end %></button>
        <!-- <button type="button" class="btn pmd-btn-flat pmd-ripple-effect btn-default">Action</button> -->
      </div>
        </div>
      </div>
    </div>
  <% end %>
</div> <!-- end row -->

app/views/users/index.html.erb
<br>
<br>
<br>
<br>
<p class='text-center'>testing</p>


<div class="row">
    <div class="col-xs-12">
      <div class="table-responsive">
        <table class="table table-bordered table hover">
  
    <thead>
      <tr>
        <th>User</th> 
        <th>Address1</th>
        <th>Address2</th>
        <th>Postal code</th>
        <th>State</th>
        <th>Country</th>
        <th>Price</th>
        <th>Room type</th>
        <th>Description</th>
        <th>Availability</th>
        <th>Bedroom</th>
        <th>Bathroom</th>
        <th>Preview Pic</th>
        <th>Action</th>
      </tr>
    </thead> 


     <tbody> 
      <% @listings.each do |listing| %>
         <tr> 
          <td><%= listing.user.username %></td> 
          <td><%= listing.address1 %></td>
          <td><%= listing.address2 %></td>
          <td><%= listing.postal_code %></td>
          <td><%= listing.state %></td>
          <td><%= listing.country %></td>
          <td><%= listing.price %></td>
          <td><%= listing.room_type %></td>
          <td><%= listing.description %></td>
          <td><%= listing.availability %></td>
          <td><%= listing.bedroom %></td>
          <td><%= listing.bathroom %></td>
           <td><% if listing.photos.length > 0 %>
              <%= image_tag listing.photos.first, id:"listing_preview"%>
              <% else %>
              <img id="listing_preview" src="/assets/no-preview.jpg">
              <% end %>
          </td>  
             <td><%= link_to 'Show', listing %></td>      
          <% if current_user.id == listing.user_id %>
            
            <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
            <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
 </div> 
 </div>
 </div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user, remote: true do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="password-field">
    <%= form.label :password %>
    <%= form.password_field :password %>
    </div>

    <div class="submit-field">
      <%= form.submit %>
    </div>
  <% end %>

  <div class="other-links">
    <%= link_to t(".sign_in"), sign_in_path, id: "new_link", remote: true %>
  </div>




</div>
<%= link_to "Sign in with Facebook", "/auth/facebook" %>

<div class="login"></div>

app/views/users/new.js.erb
$('#new_link').hide().after('<%= j render ("form")%>')