config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  root 'users#home'

  # start of clearance routes
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end


  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"


# end of clearance routes

  resources :listings 
  get "/mylistings" => "listings#userlisting", :as => :listing_user

  resources :users, only: [:edit, :update, :index]
  get '/users' => 'users#index', :as => :users_index

  resources :bookings, only: [:create, :destroy, :show, :edit, :update, :index]


  resources :searches, only: [:create]
  post '/search', to: 'listings#search', as: 'search' 

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  

  # get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  # delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  get '/:id', to: 'listings#show'


  post 'braintree/checkout'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->

    <!-- <link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css"> -->
    <!-- Jquery js -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    
    <!-- Bootstrap js -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Sidebar js -->
    <script type="text/javascript" language="javascript" src="http://propeller.in/components/sidebar/js/sidebar.js"></script>

    <!-- Propeller ripple effect js -->
    <script type="text/javascript" language="javascript" src="http://propeller.in/components/button/js/ripple-effect.js"></script>

    <!-- Propeller dropdown js -->
    <script type="text/javascript" src="http://propeller.in/components/dropdown/js/dropdown.js"></script>

    <!-- Propeller hover dropdown-->
    <script src="http://propeller.in/components/dropdown/js/bootstrap-hover-dropdown.js"></script>

    <!-- Propeller modal js -->
    <script type="text/javascript" src="http://propeller.in/components/modal/js/modal.js"></script>



    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   

  </head>

  <body>
    <!-- Nav menu with user information -->
    <nav class="navbar navbar-inverse navbar-fixed-top pmd-navbar pmd-z-depth">
      <div class="container-fluid">
        <!-- User information -->
        <div class="dropdown pmd-dropdown pmd-user-info pull-left">
            <div class="media-left" style="height: 70px;padding-top: 15px;">
              <% if current_user != nil %>
                <% if current_user.avatar.thumb.url != nil %>
                  <%= link_to users_index_path do %><%= image_tag current_user.avatar.thumb.url, class:"avatar-image thick-green-border", id:'nav-avatar'%><% end %>
                <%else%>
                   <%= link_to users_index_path do %><img class="smaller-image thick-green-border" src="/assets/user_default.png"><% end %>
                <% end %>
            <%else%> 
                 <%= link_to users_index_path do %><img class="smaller-image thick-green-border" src="/assets/user_default.png"><% end %>
            <% end %>
            </div>
            <div class="media-body media-middle">
              <% if current_user != nil %>
                 <%= link_to users_index_path do %><h4 style="color: brown">Welcome, <%=current_user.username%></h4><% end %>
               <%else%>
                 <%= link_to users_index_path do %><h4 style="color: brown">Welcome, Guest</h4><% end %>
              <% end %>
            </div>
        </div>

        <!--Hover dropdown with divider-->
        <div class="col-sm-4 pull-middle" style="height: 70px;padding-top: 15px;"">
            <span class="pmd-dropdown clearfix">
                <button class="btn pmd-ripple-effect btn-primary dropdown-toggle pmd-dropdown-hover" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-expanded="true">My Profile <span class="caret"></span></button>
                <ul aria-labelledby="dropdownMenuDivider" role="menu" class="dropdown-menu">
                    <li role="presentation"><%= link_to listing_user_url do %>My Property Listing<% end%></li>
                    <li role="presentation"><a href="javascript:void(0);" tabindex="-1" role="menuitem"><%= link_to bookings_path do %>My Booking<% end %></a></li>
                    
                    <li role="presentation"><a href="javascript:void(0);" tabindex="-1" role="menuitem">Summary</a></li>
                    <li class="divider" role="presentation"></li>
                    <li role="presentation"><a href="javascript:void(0);" tabindex="-1" role="menuitem">
                        <% if signed_in? -%>
                          <%= link_to t(".sign_out"), sign_out_path, method: :delete %>
                        <% else -%>
                          <%= link_to t(".sign_in"), sign_in_path %>
                        <% end -%></a>
                    </li>
                </ul>
            </span>
         </div> 

         <!-- search using scope -->  
           <!-- Search form -->
         

          <!-- <div>
            <%#= form_tag search_path, method: "get" do |f| %>
              <%#= text_field_tag :term, params[:term],placeholder: "type text here" %>
              <%#= submit_tag 'search', class: 'btn btn-primary'%>
            <%# end %>  
          </div>
 -->
          
            <!-- <p>
              <%#= text_field_tag :search, params[:search]%>
              <%#= submit_tag "Search", :name => nil %>
            </p>
          <%# end %> -->

        <!-- search -->
        <div class="col-sm-4 pull-right">
        <form class="navbar-form">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search">
              <div class="input-group-btn">
                <button class="btn btn-default btn-sm" type="submit">
                  <i class="glyphicon glyphicon-search"></i>
                </button>
              </div>
          </div>  
        </form>
        </div> 
    </nav>
        
  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

<% if signed_in? -%>
  <%= link_to 'edit', edit_user_path(current_user) %>
<% end %>
  

  <div id="yield-content">
    <%= yield %>
  </div>


  </body>
</html>